### ISSUE TITLE
How to use this plugin with "jade" based templates?

### ISSUE THREAD

**Issue by pr4bh4sh** [tea3/hexo-generator-amp#13]
I'm using https://github.com/tufu9441/maupassant-hexo for a template. Can you convert below to jade equivalent. 

```
  <% if (is_post() && config.generator_amp){ %>
    <link rel="amphtml" href="./amp/index.html">
  <% } %>
```

**Comment by tea3** [comment]
Hi, @pr4bh4sh .
Please edit `themes/maupassant/layout/base.jade`.

```  base.jade
html(lang='#{config.language}')
  head
    //- Please place the following code.
    if is_post() && config.generator_amp
      link(rel="amphtml", href='./amp/index.html')
```

**Comment by pr4bh4sh** [comment]
It worked.
however, the content its generating seems messed up.

<img width="262" alt="screen shot 2016-11-02 at 4 46 31 pm" src="https://cloud.githubusercontent.com/assets/6311526/19926617/9a17f478-a11b-11e6-9972-3b4d149c2c4e.png">

I was expecting something like `./amp/:title` and it is generating `./:titleamp`.
My understing from the current outputs is, it generates amp pages along with the normal pages and with the help of your plugin whenever google sees `rel="amphtml"` it show the url of the amp page.
Am I missing something in configurations?
My configuration file contents
```
theme: maupassant

generator_amp:
  templateDir: amp #template which generate amp tags
  assetDistDir: amp-dist #assests of the template
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false
```
