### ISSUE TITLE
How to disable copying template files?

### ISSUE THREAD

**Issue by katashin** [tea3/hexo-generator-amp#28]
It seems like hexo-generator-amp always generates sample template even if I specify existing `templateDir` in config file. Is there any way to disable this behavior or I'm just missing something?

The template directory has `.ejs`, `.css` and images directly under itself like below:

```
amp_template/
├── amp.css
├── amp.ejs
├── sample-avator.png
├── sample-logo.png
├── sample-placeholder.png
├── sample-substituteTitleImage.png
└── sample-yoursite-logo.png
```

## Environment Info

OS version

- macOS 10.12.5

Node version(`node -v`)
```
$ node -v
v6.10.3
```

Your site `_config.yml`
```
...
generator_amp:
  templateDir:  amp_template
  assetDistDir: amp
  cssFilePath: amp.css
  templateFilePath: amp.ejs
  logo:
    path:   sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: true
  validateAMP: true
...
```

Plugin version(`npm ls --depth 0`)
```
├── hexo@3.3.7
├── hexo-filter-highlight@0.0.3
├── hexo-generator-amp@3.0.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-render-pug@1.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.0
└── node-pre-gyp@0.6.36 extraneous
```
