### ISSUE TITLE
How to designate common title image?

### ISSUE THREAD

**Issue by sanori** [tea3/hexo-generator-amp#45]
In https://github.com/tea3/hexo-generator-amp/wiki/More-Settings#front-matter-option
you said that someone can designate the image of BlogPosting by setting ampSettings.titleImage.path.
the path seems to be relative to the resource directory of each post.

If I want to designate common images, such as different by posting categories, not each post,
how can I point the image?
Is the only way to copy same image to same post resource directory?

**Comment by tea3** [comment]
@sanori 
Thank you for using this plugin.

If you want to designate common images, you shouldn't set the frontmatter option.
To use common images , please set the `substituteTitleImage` option.
https://github.com/tea3/hexo-generator-amp/wiki/More-Settings#substitutetitleimage 

```
# _config.yml
#  hexo-generator-amp ：： Advanced Settings of hexo-amp-generator
generator_amp:
  substituteTitleImage: 
    path:   sample/sample-substituteTitleImage.png    # Can also specify external URL
    width:  1024   # width >= 696px
    height: 800
```
