### ISSUE TITLE
CSS syntax error in tag 'style amp-custom'

### ISSUE THREAD

**Issue by EdisonJwa** [tea3/hexo-generator-amp#53]
## BUG

I'm using the theme [hexo-theme-suka](https://github.com/SukkaW/hexo-theme-suka) and I was added the [`generator_amp`](https://github.com/tea3/hexo-generator-amp#1-edit-your-theme) part to the theme's file  ([`themes/suka/layout/_partial/head/index.ejs`](https://paste.ubuntu.com/p/SXxbsvJvxx/))'s first line

But when I was trying to test my blog via https://validator.ampproject.org , I got this error

``` diff
- CSS syntax error in tag 'style amp-custom' - incomplete declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 290
  
- CSS syntax error in tag 'style amp-custom' - invalid declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 309
  
- CSS syntax error in tag 'style amp-custom' - incomplete declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 317
  
- CSS syntax error in tag 'style amp-custom' - invalid declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 337
  
- CSS syntax error in tag 'style amp-custom' - incomplete declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 378
  
- CSS syntax error in tag 'style amp-custom' - invalid declaration.AUTHOR_STYLESHEET_PROBLEM line 1744, column 392

```

This is the error part.
```css
#hexo-amp-id-1{color:#DB4D6D;}#hexo-amp-id-2{color:#DB4D6D;}#hexo-amp-id-3{color:#DB4D6D;}#hexo-amp-id-4{color:#DB4D6D;}#hexo-amp-id-5{color:#DB4D6D;}#hexo-amp-id-6{background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px}#hexo-amp-id-7{display:inline-block;padding:2px 3px}#hexo-amp-id-8{height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white}#hexo-amp-id-9{display:inline-block;padding:2px 3px}
```
the problem is  I could't find how is this part comes from, and how to fix it
(exclude the first minus sign)
```diff
- &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot
```

the is [Example HTML file](https://gist.github.com/EdisonJwa/5d113d795bda8a3e8b2826c69b31d0ab) to this full page

## Environment Info

OS version

- OSX 10.14

Node version(`node -v`)
```
v12.11.1
```

Your site `_config.yml`
```yml
generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: true   # To display warning, please set true.
  generateAmpPath: amp/archives/:abbrlink/

```

Plugin version(`npm ls --depth 0`)
```cmd
hexo-site@0.0.0 /Users/edisonjwa/Documents/git/Hexo-CI
├── core-js@3.2.1
├── hexo@3.9.0
├── hexo-abbrlink@2.0.5
├── hexo-cdnify@0.0.2
├── hexo-cli@3.0.0
├── hexo-generator-amp@3.2.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.6
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-spoiler@1.5.2
├── hexo-tag-aplayer@3.0.4
├── hexo-uglify@1.0.0
└── node-pre-gyp@0.12.0
```
